---
title: "README"
author: "Baxter Lowell"
format: gfm
editor: visual
prefer-html: true
execute:
  echo: false
---


```{r}
# read in data (both USA and global oil exports)

library(tidyverse)
library(readr)
library(dplyr)

global_exports_oil <- read.csv(here::here("data/global_oil_exports.csv"), row.names = NULL)

usa_exports <- read.csv(here::here("data/trade_data.csv"), row.names = NULL)

# cleaning up USA oil exports data

usa_exports_clean = usa_exports %>%
  select(c("reporterISO","reporterDesc", "partnerDesc", "partnerISO", "cmdDesc", "altQty", "fobvalue")) %>%
  rename(
    "Exporter" = "reporterISO",
    "Importer" = "partnerISO",
    "Product" = "cmdDesc",
    "quantity_bbl" = "altQty",
    "value_usd" = "fobvalue"
  )%>%
  mutate(
    partnerDesc = recode(partnerDesc, 
                     "Korea" = "Rep. of Korea"
                     )
  )
  

global_exports_clean = global_exports_oil %>%
   select(c("reporterISO", "partnerISO", "reporterDesc", "partnerDesc", "cmdDesc", "altQty", "fobvalue")) %>%
  rename(
    "Exporter" = "reporterISO",
    "Importer" = "partnerISO",
    "Product" = "cmdDesc",
    "quantity_bbl" = "altQty",
    "value_usd" = "fobvalue"
  )%>%
  mutate(
    partnerDesc = recode(partnerDesc, 
                     "Korea" = "Rep. of Korea"
                     )
  )%>%
   slice(-560)
```

### Data

For this project I am looking at global crude oil trade data from 2023. My data comes from the United Nations Comtrade Data set, which is a comprehensive database for global trade, including hundreds of products, imports and exports, and more. I also am using the Happy Planet Index to introduce some additional variables.

### Questions

I want to explore both trade networks of crude oil for both the United States and the entire world. Some basic questions I am looking to answer are; Who does the US export the most oil to? Does exporting oil help to lead to a better quality of life? What do trade networks look like for individual countries?

The goal of this project is to create a tool that allows users to analyze trade networks of a country of their choosing. Tools like this can be used to try and predict who will be most effected by global events that cause oil shortages or supply issues.
